### ISSUE TITLE
Got wrong parameter dimensions when runing bundle models in model-zoo

### ISSUE THREAD

**Issue by zmsunnyday** [Project-MONAI/GenerativeModels#426]
Hi MONAI team,

I was trying to run the models in GenerativeModels model-zoo, but got errors for both brain_image_synthesis_latent_diffusion_model and cxr_image_synthesis_latent_diffusion_model. It seemed like the parameter dimensions in models and checkpoints were misaligned.
MONAI version: monai                   1.1.0

`python -m monai.bundle run save_jpg --config_file configs/inference.json --prompt "Small right-sided pleural effusion" --guidance_scale 7.0`
```
2023-10-23 07:42:58,855 - INFO - --- input summary of monai.bundle.scripts.run ---
2023-10-23 07:42:58,855 - INFO - > runner_id: 'save_jpg'
2023-10-23 07:42:58,855 - INFO - > config_file: 'configs/inference.json'
2023-10-23 07:42:58,856 - INFO - > prompt: 'Small right-sided pleural effusion'
2023-10-23 07:42:58,856 - INFO - > guidance_scale: 7.0
2023-10-23 07:42:58,856 - INFO - ---


Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/__main__.py", line 18, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/scripts.py", line 742, in run
    return [parser.get_parsed_content(i, lazy=True, eval_expr=True, instantiate=True) for i in ensure_tuple(runner_id_)]
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/scripts.py", line 742, in <listcomp>
    return [parser.get_parsed_content(i, lazy=True, eval_expr=True, instantiate=True) for i in ensure_tuple(runner_id_)]
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/config_parser.py", line 271, in get_parsed_content
    return self.ref_resolver.get_resolved_content(id=id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/reference_resolver.py", line 185, in get_resolved_content
    return self._resolve_one_item(id=id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/reference_resolver.py", line 155, in _resolve_one_item
    self._resolve_one_item(id=d, waiting_list=waiting_list, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/reference_resolver.py", line 155, in _resolve_one_item
    self._resolve_one_item(id=d, waiting_list=waiting_list, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/reference_resolver.py", line 155, in _resolve_one_item
    self._resolve_one_item(id=d, waiting_list=waiting_list, **kwargs)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/reference_resolver.py", line 167, in _resolve_one_item
    item.evaluate(globals={f"{self._vars}": self.resolved_content}) if run_eval else item
  File "/usr/local/lib/python3.8/dist-packages/monai/bundle/config_item.py", line 366, in evaluate
    return eval(value[len(self.prefix) :], globals_, locals)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1918, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DiffusionModelUNet:
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
        size mismatch for down_blocks.1.attentions.0.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for down_blocks.1.attentions.1.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
        size mismatch for down_blocks.1.attentions.1.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for down_blocks.2.attentions.0.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for down_blocks.2.attentions.0.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for down_blocks.2.attentions.1.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for down_blocks.2.attentions.1.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for middle_block.attention.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for middle_block.attention.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for up_blocks.0.attentions.0.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for up_blocks.0.attentions.0.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for up_blocks.0.attentions.1.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for up_blocks.0.attentions.1.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for up_blocks.0.attentions.2.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([6144, 768]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for up_blocks.0.attentions.2.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([6144]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
        size mismatch for up_blocks.1.attentions.0.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
        size mismatch for up_blocks.1.attentions.1.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.linear1.weight: copying a param with shape torch.Size([4096, 512]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
        size mismatch for up_blocks.1.attentions.2.transformer_blocks.0.ff.linear1.bias: copying a param with shape torch.Size([4096]) from checkpoint, the shape in current model is torch.Size([2048]).
```

**Comment by marksgraham** [comment]
Thats strange - can you confirm you have the latest version of MONAI Generative installed?

**Comment by zmsunnyday** [comment]
I cloned the repository last week and installed it by running setup.py. I believe it's the lastest version.

**Comment by zmsunnyday** [comment]
The problem has been solved by starting from a clean environment and codebase. Thank you @marksgraham !
